In [1]:
# Realizar a instalação da biblioteca localmente
# pip install numpy -q 

In [2]:
# Fazer a importação da biblioteca e usar um alias para chamar suas funções
import numpy as np

In [3]:
first_array = np.array([1,2,3,4]) # instanciando um array 1D usando lista
second_array = np.array((0.1, 0.2, 0.3, 0.4)) # instanciando um array 1D usando tupla
type(first_array), type(second_array)

(numpy.ndarray, numpy.ndarray)

In [4]:
first_array.dtype, second_array.dtype # descobrindo os tipos de dados dos arrays

(dtype('int32'), dtype('float64'))

In [5]:
third_array = np.array([1,2,3,4], dtype=np.uint8)
third_array.dtype # instanciando um array 1D especificando o tipo de dado

dtype('uint8')

In [6]:
first_matrix = np.array([[2,3,6],[4,9,0]], dtype=np.int16) # instanciando um array 2D
first_matrix.size # quantidade de elementos
first_matrix.shape # dimensões (axis 0, axis 1)

(2, 3)

In [7]:
zeros_array = np.zeros(7, dtype=np.int32)
zeros_array # instanciando um array 1D com o valor 0

array([0, 0, 0, 0, 0, 0, 0])

In [8]:
ones_array = np.ones([10, 2], dtype=np.float32)
ones_array # instanciando um array 2D com o valor 1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [9]:
matrix_array = np.eye(5, dtype=int)
matrix_array # instanciando uma matrix quadrada com o valor 1 na diagonal

# essa função não necessariamente requer uma matriz quadrada,
# basta estabelecer o valor das dimensões

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [10]:
np.arange(2, 11, 2, dtype=np.uint8) # retorna um array com o range estabelecido

array([ 2,  4,  6,  8, 10], dtype=uint8)

In [11]:
np.linspace(2, 10, num=8) # retorna um array que divide o intervalo em "num=" partes

array([ 2.        ,  3.14285714,  4.28571429,  5.42857143,  6.57142857,
        7.71428571,  8.85714286, 10.        ])

In [12]:
np.random.random(5) # retorna um array 1D de números aleatórios com a quantidade especificada

array([0.03401614, 0.14180742, 0.51759154, 0.15295105, 0.53984465])

In [13]:
np.random.seed(0) # usando a seed para retornar resultados semelhantes ao instrutor
np.random.random([5, 3]) # retorna um array 2D com a mesma proposta

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [14]:
np.random.seed(0) # usando a seed para retornar resultados semelhantes ao instrutor
np.random.randint(1, 10, 50) # retorna um array de números aleatórios no range especificado

# Nota-se que o valor do segundo parâmetro não é inclusivo nesse caso

array([6, 1, 4, 4, 8, 4, 6, 3, 5, 8, 7, 9, 9, 2, 7, 8, 8, 9, 2, 6, 9, 5,
       4, 1, 4, 6, 1, 3, 4, 9, 2, 4, 4, 4, 8, 1, 2, 1, 5, 8, 4, 3, 8, 3,
       1, 1, 5, 6, 6, 7])

In [15]:
array_shape = np.arange(12) # instanciando um array 1D usando arange
array_shape.shape, array_shape

((12,), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [16]:
array_reshape = array_shape.reshape(4,3) # reshaping o array 1D em 2D
array_reshape.shape, array_reshape

((4, 3),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [23]:
array_shape[0] is array_reshape[0,0]

False

In [24]:
array_reshape[3,2] = 200
array_shape # essa atribuição demonstra que o elemento é alterado em ambos os arrays

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200])

In [19]:
array_copy = array_shape.reshape(3, 4).copy()
array_copy # fazer uma cópia quebra o vínculo especificado anteriormente

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

In [20]:
vertical_array_stack = np.vstack((first_matrix, array_reshape))
vertical_array_stack # Vertical Stack

array([[  2,   3,   6],
       [  4,   9,   0],
       [  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10, 200]])

In [21]:
first_array.astype(np.uint16)
array_shape.astype(np.uint16)

horizontal_array_stack = np.hstack((first_array, array_shape))
horizontal_array_stack # Horizontal Stack

array([  1,   2,   3,   4,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10, 200])